/**
 * This file is generated based on the OpenAPI specifications.
 * Do not edit this file directly.
 */

// From comments.yaml

/**
 * Represents the user information associated with a comment.
 */
export interface CommentUser {
  id: string;
  nickname: string | null;
  avatar_url: string | null;
}

/**
 * Represents a single comment, which can be nested.
 */
export interface Comment {
  id: string;
  user_id: string;
  user: CommentUser;
  parent_type: 'page' | 'question';
  parent_id: string;
  parent_comment_id: string | null;
  content: string;
  status: 'visible' | 'hidden_by_moderator' | 'reported';
  created_at: string; // ISO 8601 date string
  replies?: Comment[];
}

/**
 * The payload required to create a new comment.
 */
export interface CreateCommentPayload {
  parentType: 'page' | 'question';
  parentId: string;
  content: string;
  parentCommentId?: string | null;
}

/**
 * The structure of a successful paginated response for comments.
 */
export interface PaginatedCommentsResponse {
  ok: boolean;
  data: {
    items: Comment[];
    total: number;
    nextCursor: string | null;
  };
}

/**
 * A generic error response from the API.
 */
export interface ErrorResponse {
  ok: boolean;
  message: string;
}


// From pdf 伴学.yaml

export interface MultilingualText {
  en: string;
  zh: string;
  [key: string]: string;
}

export interface QuizOption {
  id: string;
  text: MultilingualText;
}

export interface QuestionUserStats {
  totalAttempts: number;
  correctAttempts: number;
}

export interface QuestionSocialStats {
  userId: string;
  nickname: string;
  avatarUrl: string;
  totalAttempts: number;
  correctAttempts: number;
}

export interface Question {
  id: string;
  page_number: number;
  difficulty: 'easy' | 'medium' | 'hard';
  choice_type: 'single_choice' | 'multiple_choice';
  question_text: MultilingualText;
  options: QuizOption[];
  correct_answers: string[];
  explanation: MultilingualText;
  created_at: string; // ISO 8601 date string
  updated_at: string; // ISO 8601 date string
  userStats?: QuestionUserStats | null;
  answeredByUsers?: QuestionSocialStats[];
}

/**
 * Represents a node in the knowledge graph (e.g., a concept, an entity).
 * Based on companion-data.yaml.
 */
/**
 * Represents a Page node in the graph.
 */
export interface PageNode {
  id: string;
  number: number;
  name: string;
  type: 'Page';
}

/**
 * Represents a Concept node (KnowledgePoint or Topic) in the graph.
 */
export interface ConceptNode {
  id: string;
  raw_id: string;
  type: 'KnowledgePoint' | 'Topic';
  name_en: string;
  name_zh: string;
  name_es?: string;
  name_fr?: string;
  name_ja?: string;
  name_de?: string;
  definition_en?: string;
  definition_zh?: string;
  definition_es?: string;
  definition_fr?: string;
  definition_ja?: string;
  definition_de?: string;
}

/**
 * A graph node can be one of several types, discriminated by the `type` property.
 */
export type GraphNode = PageNode | ConceptNode;

/**
 * Represents a relationship between two nodes in the graph.
 */
export interface GraphRelationship {
  type: string;
  source: string; // ID of the source node
  target: string; // ID of the target node
}

/**
 * Defines the structure for graph data returned by the API.
 */
export interface GraphData {
  nodes: GraphNode[];
  relationships: GraphRelationship[];
}

export interface CompanionData {
  pageNumber: number;
  pageImageUrl: string;
  graph: GraphData | null;
  questions: Question[];
}

// From question submission endpoint

/**
 * Payload for submitting an answer to a question.
 */
export interface QuestionSubmissionPayload {
  selectedAnswers: string[];
}

/**
 * Detailed analysis of a multiple-choice answer.
 */
export interface AnswerAnalysis {
  correctSelections: string[];
  incorrectSelections: string[];
  missedCorrectAnswers: string[];
}

/**
 * The result returned after submitting a question answer.
 */
export interface QuestionSubmissionResult {
  isCorrect: boolean;
  isPartiallyCorrect?: boolean;
  correctAnswers: string[];
  explanation: MultilingualText;
  answerAnalysis?: AnswerAnalysis;
}

// From various user & review endpoints

export type ApiError = ErrorResponse;

export interface UserProfile {
  id: string;
  email: string;
  nickname: string;
  avatar_url: string;
  created_at: string; // ISO 8601 date string
  updated_at: string; // ISO 8601 date string
  roles: string[];
}

export interface UserSyncPayload {
  id: string;
  email: string;
  nickname: string;
  avatar_url: string;
}

export interface User extends UserProfile {}

export interface UserUpdatePayload {
  nickname?: string;
  avatar_url?: string;
}

export type DashboardStats = any;


// From review.yaml

export interface DueReviewQuestion extends Question {
  last_reviewed_at: string | null;
  review_stage: number;
}

export interface DueReviewsResponse {
  due_questions: DueReviewQuestion[];
}

// From leaderboard.yaml

export interface LeaderboardUser {
  userId: string;
  nickname: string;
  avatarUrl: string | null;
  totalAttempts: number;
  correctAttempts: number;
  accuracy: number;
}

export type LeaderboardSortBy = 'totalAttempts' | 'correctAttempts' | 'accuracy';

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

export type SearchResults = any;

// From ai-chat.yaml (v1.1.0)

/**
 * Represents a part of a multi-modal message.
 */
export interface ContentPart {
  type: 'text' | 'image_url';
  text?: string;
  image_url?: {
    url: string;
  };
}

/**
 * Represents a single message in the conversation.
 */
export interface AiMessage {
  role: 'user' | 'assistant' | 'system';
  content: string | ContentPart[];
}

/**
 * The request payload for the AI completion endpoint.
 */
export interface AiCompletionRequest {
  model: string;
  messages: AiMessage[];
  system_prompt?: string;
  response_format?: {
    type: 'text' | 'json_object';
  };
  stream?: boolean;
}

/**
 * The response payload from a non-streaming AI completion.
 */
export interface AiCompletionResponse {
  ok: boolean;
  response: string | object;
}

export interface AiInteraction {
  id: string;
  user_id: string;
  parent_type: 'node' | 'question' | 'pdf' | null;
  parent_id: string | null;
  // NOTE: Backend now returns 'messages' as a JSON string instead of 'prompt'.
  // This deviates from the current OpenAPI spec.
  messages: string; // JSON string of AiMessage[]
  response: string;
  model_used: string | null;
  metadata: string | null; // Assuming JSON string
  created_at: string; // ISO 8601 date string
}

export interface CreateAiInteractionPayload {
  parent_type?: 'node' | 'question' | 'pdf' | null;
  parent_id?: string | null;
  messages: AiMessage[];
  response: string;
  model_used?: string | null;
  metadata?: string | null; // Assuming JSON string
}

""
